/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calculator_adaptor add.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CALCULATOR_ADAPTOR_H
#define CALCULATOR_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface com.example.calculator
 */
class CalculatorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.example.calculator")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.example.calculator\">\n"
"    <method name=\"add\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"result\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CalculatorAdaptor(QObject *parent);
    ~CalculatorAdaptor() override;

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int add();
Q_SIGNALS: // SIGNALS
};

#endif
