/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calculator_adaptor add.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "calculator_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CalculatorAdaptor
 */

CalculatorAdaptor::CalculatorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CalculatorAdaptor::~CalculatorAdaptor()
{
    // destructor
}

int CalculatorAdaptor::add()
{
    // handle method call com.example.calculator.add
    int result;
    QMetaObject::invokeMethod(parent(), "add", Q_RETURN_ARG(int, result));
    return result;
}

