/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calculator_adaptor calculator_interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CALCULATOR_ADAPTOR_H
#define CALCULATOR_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
// class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.example.Calculator
 */
class CalculatorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.example.Calculator")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.example.Calculator\">\n"
"    <method name=\"add\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"a\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"b\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"sum\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CalculatorAdaptor(QObject *parent);
    virtual ~CalculatorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int add(int a, int b);
Q_SIGNALS: // SIGNALS
};

#endif
