/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calculator_adaptor calculator_interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "calculator_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CalculatorAdaptor
 */

CalculatorAdaptor::CalculatorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CalculatorAdaptor::~CalculatorAdaptor()
{
    // destructor
}

int CalculatorAdaptor::add(int a, int b)
{
    // handle method call org.example.Calculator.add
    int sum;
    QMetaObject::invokeMethod(parent(), "add", Q_RETURN_ARG(int, sum), Q_ARG(int, a), Q_ARG(int, b));
    return sum;
}

