/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p calculator_proxy add.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "calculator_proxy.h"

/*
 * Implementation of interface class ComExampleCalculatorInterface
 */

ComExampleCalculatorInterface::ComExampleCalculatorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComExampleCalculatorInterface::~ComExampleCalculatorInterface()
{
}

