/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p calculator_proxy add.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CALCULATOR_PROXY_H
#define CALCULATOR_PROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.example.calculator
 */
class ComExampleCalculatorInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.example.calculator"; }

public:
    ComExampleCalculatorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~ComExampleCalculatorInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> add()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("add"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace example {
    using calculator = ::ComExampleCalculatorInterface;
  }
}
#endif
